# SPDX-License-Identifier: GPL-2.0-only

# Localized KCONFIG settings
CONFIG_TOUCHSCREEN_LXS := y
CONFIG_TOUCHSCREEN_LXS_SW82907 := y

# Flags to pass into C preprocessor
ccflags-y += -DCONFIG_TOUCHSCREEN_LXS=1 \
	-DCONFIG_TOUCHSCREEN_LXS_SW82907=1 \
	-D__SOMC_CUSTOM_DRM_NOTIF=1 \
	-D__SOMC_CUSTOM_INPUT_CTRL=1 \
	-D__SOMC_CUSTOM_POWER_CTRL=1 \
	-D__SOMC_CUSTOM_GPIO_SHARE=1
